package Ventanas;

import com.mycompany.mesaayuda.model.SessionUsuario;
import com.mycompany.mesaayuda.model.Ticket;
import com.mycompany.mesaayuda.servicios.DaoUsuario;
import com.mycompany.mesaayuda.servicios.DepartamentoDAO;
import com.mycompany.mesaayuda.servicios.PrioridadDAO;
import com.mycompany.mesaayuda.servicios.TicketDAO;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author demo_
 */
public class Seguimiento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Seguimiento.class.getName());

    /**
     * Creates new form Seguimiento
     */
    public Seguimiento() {
        initComponents();
        
               
    }
    
    public Seguimiento(Ticket ticket) {
    initComponents();
    
    DaoUsuario DAO = new DaoUsuario();
        
    Nombretxt.setText(SessionUsuario.getNombreUsuario());
        
    String nombreRol = DAO.obtenerNombreRol(SessionUsuario.getIdRol());
    roltxt.setText(nombreRol != null ? nombreRol : "Sin rol asignado");
    
    DepartamentoDAO dao = new DepartamentoDAO();
    dao.cargarDepartamentos(DepartamentoBox); 

    String nombreDepartamento = dao.obtenerNombreDepartamento(ticket.getIdDepartamento()); 
    DepartamentoBox.setSelectedItem(nombreDepartamento);
    
    PrioridadDAO priDao = new PrioridadDAO();
    priDao.cargarPrioridades(PrioridadBox);

    String nombrePrioridad = priDao.obtenerNombrePorId(ticket.getIdPrioridad());  
    PrioridadBox.setSelectedItem(nombrePrioridad); 

        
    Foliotxt.setText(ticket.getFolio());
    Titulotxt.setText(ticket.getTitulo());
    DescripcionArea.setText(ticket.getDescripcion());
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estadobox = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Titulotxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescripcionArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        asignadotxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tiempotxt = new javax.swing.JTextField();
        HistorialButton = new javax.swing.JButton();
        TicketButton1 = new javax.swing.JButton();
        BottonRegresar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Foliotxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        estadobox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Actualizaciontxt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Nombretxt = new javax.swing.JTextField();
        roltxt = new javax.swing.JTextField();
        DepartamentoBox = new javax.swing.JComboBox<>();
        PrioridadBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Estadobox.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seguimiento de tickets");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Titulo: ");

        jLabel3.setText("Descripcion:");

        DescripcionArea.setColumns(20);
        DescripcionArea.setRows(5);
        jScrollPane1.setViewportView(DescripcionArea);

        jLabel4.setText("Estado");

        jLabel5.setText("Asignado");

        jLabel6.setText("Departamento");

        jLabel7.setText("Ultima actualizacion");

        jLabel8.setText("Prioridad");

        jLabel9.setText("Tiempo invertido");

        HistorialButton.setBackground(new java.awt.Color(102, 102, 255));
        HistorialButton.setForeground(new java.awt.Color(255, 255, 255));
        HistorialButton.setText("Historial");
        HistorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialButtonActionPerformed(evt);
            }
        });

        TicketButton1.setBackground(new java.awt.Color(102, 102, 255));
        TicketButton1.setForeground(new java.awt.Color(255, 255, 255));
        TicketButton1.setText("Grabar");
        TicketButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketButton1ActionPerformed(evt);
            }
        });

        BottonRegresar.setBackground(new java.awt.Color(102, 102, 255));
        BottonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BottonRegresar.setText("Regresar");
        BottonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonRegresarActionPerformed(evt);
            }
        });

        jLabel10.setText("Folio");

        Foliotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoliotxtActionPerformed(evt);
            }
        });

        estadobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1,Abierto", "2,Cerrado" }));
        estadobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoboxActionPerformed(evt);
            }
        });

        Actualizaciontxt.setColumns(20);
        Actualizaciontxt.setRows(5);
        jScrollPane2.setViewportView(Actualizaciontxt);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4781818_account_avatar_face_man_people_icon.png"))); // NOI18N
        jButton1.setBorderPainted(false);

        Nombretxt.setEditable(false);

        roltxt.setEditable(false);

        DepartamentoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentoBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EstadoboxLayout = new javax.swing.GroupLayout(Estadobox);
        Estadobox.setLayout(EstadoboxLayout);
        EstadoboxLayout.setHorizontalGroup(
            EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(EstadoboxLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstadoboxLayout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstadoboxLayout.createSequentialGroup()
                                        .addComponent(Titulotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(129, 129, 129))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstadoboxLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(217, 217, 217))
                                    .addComponent(asignadotxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EstadoboxLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EstadoboxLayout.createSequentialGroup()
                                        .addGap(234, 234, 234)
                                        .addComponent(jLabel2))
                                    .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstadoboxLayout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(estadobox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(EstadoboxLayout.createSequentialGroup()
                                                    .addGap(28, 28, 28)
                                                    .addComponent(jLabel4)))
                                            .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(EstadoboxLayout.createSequentialGroup()
                                                    .addGap(33, 33, 33)
                                                    .addComponent(jLabel8)
                                                    .addGap(70, 70, 70)
                                                    .addComponent(jLabel6))
                                                .addGroup(EstadoboxLayout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(PrioridadBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(36, 36, 36)
                                                    .addComponent(DepartamentoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(25, 25, 25)
                                            .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(EstadoboxLayout.createSequentialGroup()
                                                    .addGap(26, 26, 26)
                                                    .addComponent(jLabel9))
                                                .addComponent(tiempotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(EstadoboxLayout.createSequentialGroup()
                                            .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(EstadoboxLayout.createSequentialGroup()
                                            .addGap(116, 116, 116)
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5)
                                            .addGap(46, 46, 46))))))
                        .addGap(22, 22, 22))
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EstadoboxLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(38, 38, 38)
                                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EstadoboxLayout.createSequentialGroup()
                                .addGap(375, 375, 375)
                                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Foliotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(EstadoboxLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel10)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(EstadoboxLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(HistorialButton)
                .addGap(112, 112, 112)
                .addComponent(TicketButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstadoboxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BottonRegresar)
                .addGap(14, 14, 14))
        );
        EstadoboxLayout.setVerticalGroup(
            EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadoboxLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Foliotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addComponent(Nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(Titulotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estadobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrioridadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tiempotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DepartamentoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asignadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HistorialButton)
                    .addComponent(TicketButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BottonRegresar)
                .addContainerGap())
        );

        getContentPane().add(Estadobox, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HistorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialButtonActionPerformed
    String folio = Foliotxt.getText(); 

    if (folio == null || folio.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No se ha cargado ningún folio.");
        return;
    }

    Historial historial = new Historial(this, true);
    historial.setLocationRelativeTo(this);
    historial.setVisible(true);
    }//GEN-LAST:event_HistorialButtonActionPerformed

    private void TicketButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketButton1ActionPerformed
   String folio = Foliotxt.getText();
    TicketDAO dao = new TicketDAO();
    int idTicket = dao.obtenerIdTicketPorFolio(folio);

    if (idTicket != -1) {
        Ticket actualizado = new Ticket();
        actualizado.setId(idTicket);
        actualizado.setIdPrioridad(PrioridadBox.getSelectedIndex());
        actualizado.setIdStatus(estadobox.getSelectedIndex());
        actualizado.setTiempoInvertido(tiempotxt.getText());
        actualizado.setAsignado(asignadotxt.getText());
        actualizado.setUltimaActualizacion(LocalDateTime.now().toString());

        dao.actualizarTicket(actualizado);

        String usuarioActual = SessionUsuario.getNombreUsuario(); 
        dao.registrarHistorialCambio(idTicket, usuarioActual, "Actualización desde seguimiento", actualizado);

        JOptionPane.showMessageDialog(this, "Ticket actualizado y historial registrado.");
        
        this.dispose();
        RegistroIncidencias RI=new RegistroIncidencias();
        RI.setLocationRelativeTo(this);
        RI.setVisible(true);
        
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró el ticket con folio: " + folio);
    }
    }//GEN-LAST:event_TicketButton1ActionPerformed

    private void BottonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonRegresarActionPerformed
    this.dispose();
    RegistroIncidencias RI=new RegistroIncidencias();
    RI.setLocationRelativeTo(this);
    RI.setVisible(true);
        
    }//GEN-LAST:event_BottonRegresarActionPerformed

    private void estadoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoboxActionPerformed

    private void FoliotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoliotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoliotxtActionPerformed

    private void DepartamentoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartamentoBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Seguimiento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Actualizaciontxt;
    private javax.swing.JButton BottonRegresar;
    private javax.swing.JComboBox<String> DepartamentoBox;
    private javax.swing.JTextArea DescripcionArea;
    private javax.swing.JPanel Estadobox;
    private javax.swing.JTextField Foliotxt;
    private javax.swing.JButton HistorialButton;
    private javax.swing.JTextField Nombretxt;
    private javax.swing.JComboBox<String> PrioridadBox;
    private javax.swing.JButton TicketButton1;
    private javax.swing.JTextField Titulotxt;
    private javax.swing.JTextField asignadotxt;
    private javax.swing.JComboBox<String> estadobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField roltxt;
    private javax.swing.JTextField tiempotxt;
    // End of variables declaration//GEN-END:variables
}
