package Ventanas;

import com.mycompany.mesaayuda.model.Ticket;
import com.mycompany.mesaayuda.servicios.TicketDAO;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author demo_
 */
public class Seguimiento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Seguimiento.class.getName());

    /**
     * Creates new form Seguimiento
     */
    public Seguimiento() {
        initComponents();
               
    }
    
    public Seguimiento(Ticket ticket) {
    initComponents();
    // Aquí asignas los datos del ticket a los campos visuales
    Foliotxt.setText(ticket.getFolio());
    Titulotxt.setText(ticket.getTitulo());
    DescripcionArea.setText(ticket.getDescripcion());
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estadobox = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Titulotxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescripcionArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Titulotxt2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Titulotxt3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Titulotxt5 = new javax.swing.JTextField();
        HistorialButton = new javax.swing.JButton();
        TicketButton1 = new javax.swing.JButton();
        BottonRegresar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Foliotxt = new javax.swing.JTextField();
        Titulotxt6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        PrioridadBox = new javax.swing.JComboBox<>();
        PrioridadBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Estadobox.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seguimiento de tickets");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Titulo: ");

        jLabel3.setText("Descripcion:");

        DescripcionArea.setColumns(20);
        DescripcionArea.setRows(5);
        jScrollPane1.setViewportView(DescripcionArea);

        jLabel4.setText("Estado");

        jLabel5.setText("Asignado");

        jLabel6.setText("Departamento");

        jLabel7.setText("Ultima actualizacion");

        jLabel8.setText("Prioridad");

        jLabel9.setText("Tiempo invertido");

        HistorialButton.setBackground(new java.awt.Color(102, 102, 255));
        HistorialButton.setForeground(new java.awt.Color(255, 255, 255));
        HistorialButton.setText("Historial");
        HistorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialButtonActionPerformed(evt);
            }
        });

        TicketButton1.setBackground(new java.awt.Color(102, 102, 255));
        TicketButton1.setForeground(new java.awt.Color(255, 255, 255));
        TicketButton1.setText("Grabar");
        TicketButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketButton1ActionPerformed(evt);
            }
        });

        BottonRegresar.setBackground(new java.awt.Color(102, 102, 255));
        BottonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BottonRegresar.setText("Regresar");
        BottonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonRegresarActionPerformed(evt);
            }
        });

        jLabel10.setText("Folio");

        PrioridadBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Media", "Baja" }));
        PrioridadBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrioridadBoxActionPerformed(evt);
            }
        });

        PrioridadBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1,Abierto", "2,Cerrado" }));
        PrioridadBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrioridadBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EstadoboxLayout = new javax.swing.GroupLayout(Estadobox);
        Estadobox.setLayout(EstadoboxLayout);
        EstadoboxLayout.setHorizontalGroup(
            EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(EstadoboxLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstadoboxLayout.createSequentialGroup()
                                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Titulotxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstadoboxLayout.createSequentialGroup()
                                            .addGap(107, 107, 107)
                                            .addComponent(HistorialButton)
                                            .addGap(120, 120, 120)
                                            .addComponent(TicketButton1))
                                        .addGroup(EstadoboxLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(102, 102, 102)
                                            .addComponent(jLabel8))))
                                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EstadoboxLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel9))
                                    .addGroup(EstadoboxLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Titulotxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(EstadoboxLayout.createSequentialGroup()
                                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstadoboxLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(203, 203, 203))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(EstadoboxLayout.createSequentialGroup()
                                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Titulotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(EstadoboxLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EstadoboxLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel10))
                                    .addComponent(Foliotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstadoboxLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BottonRegresar)
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PrioridadBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EstadoboxLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PrioridadBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Titulotxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Titulotxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        EstadoboxLayout.setVerticalGroup(
            EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadoboxLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Titulotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Foliotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Titulotxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Titulotxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(PrioridadBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11))
                    .addGroup(EstadoboxLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Titulotxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Titulotxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrioridadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62)
                .addGroup(EstadoboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HistorialButton)
                    .addComponent(TicketButton1))
                .addGap(18, 18, 18)
                .addComponent(BottonRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Estadobox, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HistorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialButtonActionPerformed
    String folio = Foliotxt.getText(); 

    if (folio == null || folio.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No se ha cargado ningún folio.");
        return;
    }

    Historial historial = new Historial(this, true);
    historial.setLocationRelativeTo(this);
    historial.setVisible(true);
    }//GEN-LAST:event_HistorialButtonActionPerformed

    private void TicketButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketButton1ActionPerformed
   /* String folio = Foliotxt.getText();
    TicketDAO dao = new TicketDAO();
        int idTicket = dao.obtenerIdTicketPorFolio(folio);

        if (idTicket != -1) {
    // Actualizar el ticket
    Ticket actualizado = new Ticket();
    actualizado.setId(idTicket);
    actualizado.setPrioridad(PrioridadCombo.getSelectedIndex());
    actualizado.setEstado(Estadobox.getSelectedIndex());
    actualizado.setTiempoInvertido(TiempoTxt.getText());
    actualizado.setAsignado(AsignadoTxt.getText());
    actualizado.setUltimaActualizacion(LocalDateTime.now().toString());
    dao.actualizarTicket(actualizado); // método que debes crear

    // Registrar historial
    dao.registrarHistorialCambio(idTicket, usuarioActual, "Actualización desde seguimiento", actualizado);
    
    JOptionPane.showMessageDialog(this, "Ticket actualizado y historial registrado.");
} else {
    JOptionPane.showMessageDialog(this, "No se encontró el ticket con folio: " + folio);
}
*/
    }//GEN-LAST:event_TicketButton1ActionPerformed

    private void BottonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonRegresarActionPerformed
       
        
    }//GEN-LAST:event_BottonRegresarActionPerformed

    private void PrioridadBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrioridadBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrioridadBoxActionPerformed

    private void PrioridadBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrioridadBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrioridadBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Seguimiento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottonRegresar;
    private javax.swing.JTextArea DescripcionArea;
    private javax.swing.JPanel Estadobox;
    private javax.swing.JTextField Foliotxt;
    private javax.swing.JButton HistorialButton;
    private javax.swing.JComboBox<String> PrioridadBox;
    private javax.swing.JComboBox<String> PrioridadBox1;
    private javax.swing.JButton TicketButton1;
    private javax.swing.JTextField Titulotxt;
    private javax.swing.JTextField Titulotxt2;
    private javax.swing.JTextField Titulotxt3;
    private javax.swing.JTextField Titulotxt5;
    private javax.swing.JTextField Titulotxt6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
